channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - einops=0.1.0
  - pip=19.2.3
  - pymongo=3.9.0
  - python=3.7.4
  - pytorch=1.2.0
  - spacy=2.3.2
  - pip:
    - anaforatools==1.1.0
    - rnnr==0.4.0
    - sacred==0.8.2
    - sentencepiece==0.1.91
    - text2array==0.2.0
    - tqdm==4.31.1
    - transformers==3.4.0
    - git+https://github.com/harvardnlp/pytorch-struct@9f93432#egg=torch_struct
